Model:
  batch_size: 4
  input_shape:
  - 224
  - 224
  - 3
  mode: inference
  path: resnet.ResNet50
  type: keras
Profiling:
- Platform: ATS
  latency: 34
  peak_gpu_utilization: 50
  peak_mem_utilization: 75
QoS:
  latency: '4'
